# Generated by Django 4.0.8 on 2023-04-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_passwords1_user_passwords2_user_phone_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passwords1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passwords2',
        ),
    ]
